//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCreator.SR_Categories {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_Categories.IServiceItems")]
    public interface IServiceItems {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceItems/QueryAllItems", ReplyAction="http://tempuri.org/IServiceItems/QueryAllItemsResponse")]
        Shared.XItem[] QueryAllItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceItems/QueryAllItems", ReplyAction="http://tempuri.org/IServiceItems/QueryAllItemsResponse")]
        System.Threading.Tasks.Task<Shared.XItem[]> QueryAllItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceItems/GetCategories", ReplyAction="http://tempuri.org/IServiceItems/GetCategoriesResponse")]
        string[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceItems/GetCategories", ReplyAction="http://tempuri.org/IServiceItems/GetCategoriesResponse")]
        System.Threading.Tasks.Task<string[]> GetCategoriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceItemsChannel : DataCreator.SR_Categories.IServiceItems, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceItemsClient : System.ServiceModel.ClientBase<DataCreator.SR_Categories.IServiceItems>, DataCreator.SR_Categories.IServiceItems {
        
        public ServiceItemsClient() {
        }
        
        public ServiceItemsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceItemsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceItemsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceItemsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Shared.XItem[] QueryAllItems() {
            return base.Channel.QueryAllItems();
        }
        
        public System.Threading.Tasks.Task<Shared.XItem[]> QueryAllItemsAsync() {
            return base.Channel.QueryAllItemsAsync();
        }
        
        public string[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
    }
}
